---
    name: code-maven-sonarcloud-analysis
    run-name: Sonarcloud analysis on ${{ github.base_ref || github.ref_name }} branch

    on:
      workflow_dispatch:
      pull_request:
    
    jobs:
      unit-tests:
        name: SonarCloud / Unit Tests
        timeout-minutes: 30
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@master
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            with:
              projectBaseDir: code
              args: >
                -Dsonar.branch.name=${{ github.base_ref || github.ref_name }}
    