---
    name: code-maven-sonarcloud-analysis
    run-name: Sonarcloud analysis on ${{ github.base_ref || github.ref_name }} branch

    on:
      workflow_dispatch:
      pull_request:
    
    jobs:
      unit-tests:
        name: SonarCloud / Unit Tests
        timeout-minutes: 30
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Setup IVM environment
            uses: asdf-vm/actions/install@v3

          - name: Setup Java environment vars
            run: |
              JAVA_HOME="$(asdf where java)"
              echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
              echo "JAVA_CACERTS_PATH=$JAVA_HOME/lib/security" >> $GITHUB_ENV
              echo "JAVA_CACERTS=$JAVA_HOME/lib/security/cacerts" >> $GITHUB_ENV

          - name: Run unit tests
            if: github.event_name != 'release'
            run: |
              mvn --version
              mvn -B clean verify -DskipITs -DfailIfNoTests=false -Dmaven.test.failure.ignore=false

          - name: Set Java and Node for Sonarcloud plugin
            run: echo -e "java temurin-17.0.8+7\nnodejs 20.10.0" > sonarcloud-tool_versions

          - name: Setup IVM environment
            uses: asdf-vm/actions/install@v3
            with:
              tool_versions: sonarcloud-tool_versions


          - name: Setup Java environment vars
            run: |
              JAVA_HOME="$(asdf where java)"
              echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
              echo "JAVA_CACERTS_PATH=$JAVA_HOME/lib/security" >> $GITHUB_ENV
              echo "JAVA_CACERTS=$JAVA_HOME/lib/security/cacerts" >> $GITHUB_ENV

          - name: SonarCloud / Run Maven Sonar goal
            env:
              PR_HEAD_REF: ${{ github.head_ref }}
              LOGIN: ${{ secrets.SONAR_TOKEN }}
              SONAR_SCANNER_OPTS: ''
            run: |
              mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
                -Dsonar.host.url="https://sonarcloud.io/" \
                -Dsonar.token="${LOGIN}" \
                -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
                -Dsonar.pullrequest.branch="$PR_HEAD_REF" \
                -Dsonar.pullrequest.base=${{ github.base_ref }} \
                -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} \
                -Dsonar.qualitygate.wait=true \
                -Dsonar.qualitygate.timeout=300 \
                -Dsonar.pullrequest.provider=GitHub \
                -Dsonar.pullrequest.github.repository="${{ github.repository }}" \
                -Dsonar.pullrequest.github.summary_comment=true